import { Product, Category, Store } from './types';

export const mockStore: Store = {
  id: 'store-1',
  name: 'Mi Tienda Demo',
  slug: 'mi-tienda',
  description: 'Catálogo de demostración'
};

export const categories: Category[] = [
  'Electrónica',
  'Ropa',
  'Hogar',
  'Deportes',
  'Libros',
];

export const products: Product[] = [
  {
    id: '1',
    storeId: 'store-1',
    name: 'Auriculares Inalámbricos',
    description: 'Auriculares con cancelación de ruido activa y batería de 30 horas.',
    price: 129.99,
    category: 'Electrónica',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    inStock: true,
  },
  {
    id: '2',
    storeId: 'store-1',
    name: 'Smartwatch Serie 7',
    description: 'Reloj inteligente con monitor de salud, GPS y resistente al agua.',
    price: 299.00,
    category: 'Electrónica',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    inStock: true,
  },
  {
    id: '3',
    storeId: 'store-1',
    name: 'Camiseta de Algodón Orgánico',
    description: 'Camiseta básica de alta calidad, suave y transpirable.',
    price: 24.50,
    category: 'Ropa',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    inStock: true,
  },
  {
    id: '4',
    storeId: 'store-1',
    name: 'Mochila de Senderismo',
    description: 'Mochila de 40L resistente al agua con múltiples compartimentos.',
    price: 85.00,
    category: 'Deportes',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    inStock: false,
  },
  {
    id: '5',
    storeId: 'store-1',
    name: 'Cafetera de Goteo Programable',
    description: 'Cafetera con capacidad para 12 tazas y temporizador.',
    price: 45.99,
    category: 'Hogar',
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
    inStock: true,
  },
  {
    id: '6',
    storeId: 'store-1',
    name: 'Libro: "El Arte de la Guerra"',
    description: 'Clásico tratado de estrategia militar escrito por Sun Tzu.',
    price: 15.00,
    category: 'Libros',
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
    inStock: true,
  },
  {
    id: '7',
    storeId: 'store-1',
    name: 'Zapatillas de Running',
    description: 'Zapatillas ligeras para correr con amortiguación mejorada.',
    price: 110.00,
    category: 'Deportes',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    inStock: true,
  },
  {
    id: '8',
    storeId: 'store-1',
    name: 'Lámpara de Escritorio LED',
    description: 'Lámpara regulable con puerto USB para cargar dispositivos.',
    price: 32.90,
    category: 'Hogar',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    inStock: true,
  },
  {
    id: '9',
    storeId: 'store-1',
    name: 'Chaqueta de Invierno Impermeable',
    description: 'Chaqueta abrigada ideal para bajas temperaturas y lluvia.',
    price: 150.00,
    category: 'Ropa',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
    inStock: true,
  },
  {
    id: '10',
    storeId: 'store-1',
    name: 'Cámara Mirrorless 4K',
    description: 'Cámara compacta con grabación de video en 4K y lente intercambiable.',
    price: 799.00,
    category: 'Electrónica',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
    inStock: true,
  }
];
